development:
  cloud_name: dwbchktmk
  api_key: '554752824113796'
  api_secret: IAA1T08igxhglrYQFTwMZ6r7Ekg
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: dwbchktmk
  api_key: '554752824113796'
  api_secret: IAA1T08igxhglrYQFTwMZ6r7Ekg
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: dwbchktmk
  api_key: '554752824113796'
  api_secret: IAA1T08igxhglrYQFTwMZ6r7Ekg
  enhance_image_tag: true
  static_image_support: false
